[workspace]
authors = ["jaechang <jaechang@hits.ai>"]
channels = ["conda-forge"]
name = "standigm_paper_citation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pandas = ">=3.0.0,<4"
pip = ">=25.3,<26"
